services:

  base:
    image: hhcmhub/kyon-cetc-focal-ros1-base
    stdin_open: true
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    network_mode: host
    cap_add:
      - ALL
    restart: no
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/kyon_ros1/.ssh  # ssh
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https
      - ROS_MASTER_URI
      - ROS_IP

  dev:
    extends: base 
    volumes:
      - ~/.cache/kyon-cetc-focal-ros1-base:/home/kyon_ros1/data

  xbot2_gui_server:
    extends: base
    entrypoint: bash -ic "until rostopic list; do sleep 1; done; sleep 1; cd ~/xbot2_ws/src/kyon_config; git pull origin master; xbot2_gui_server gui/gui_server_config.yaml; bash"
    restart: always

  locomotion:
    extends: base
    image: hhcmhub/kyon-cetc-focal-ros1-locomotion