context:
  session: kyon_sim
  params:
    hw_type: sim
  .defines:
    - &docker-sim focal-ros1-dev-1

# Simulation components
roscore:
  cmd: roscore
  ready_check: rostopic list

mujoco_sim:
  cmd: roslaunch kyon_mujoco kyon_world.launch arms:=true legs:=true
  ready_check: timeout 5 rostopic echo /joint_states -n 1
  depends:
    - roscore

xbot2_sim:
  cmd: xbot2-core --hw sim -C $(rospack find kyon_config)/xbot2/kyon_basic.yaml
  ready_check: timeout 5 rostopic echo /xbotcore/joint_states -n 1
  depends:
    - mujoco_sim

# Utilities for simulation
xbot2_gui_server:
  cmd: xbot2_gui_server gui/gui_server_config.yaml
  depends:
    - xbot2_sim
  
# Convenience group
sim_all:
  cmd: echo "Starting full simulation environment"
  persistent: false
  depends:
    - xbot2_sim
    - xbot2_gui_server